### ISSUE TITLE
BuildPlans are limited to 25

### ISSUE THREAD

**Issue by JohanVandeplas** [ivan-dyachenko/bamboo-status#1]
I have 159 build plans. Only the first 25 are displayed.

Implement switch for next page.
- here is how to get the next 25 entries: ?start-index=25
- here is how to get more than 25 entries: ?max-results=100

I tried to set the plan in key in the localStorage but no cigar :)

**Comment by bit-man** [comment]
Same issue here!

**Comment by JohanVandeplas** [comment]
I created a pull request I'm pretty sure that will solve the issue.. (set the max-results to 10 000). It would be better to implement paging... But I don't have the time right now :-)
